sudo: required
dist: trusty
language: cpp

os:
  - linux
  - osx

before_install: . Scripts/ci/$TRAVIS_OS_NAME/before_install.sh
install: . Scripts/ci/$TRAVIS_OS_NAME/install.sh
script: . Scripts/ci/$TRAVIS_OS_NAME/script.sh
after_success: . Scripts/ci/$TRAVIS_OS_NAME/after_success.sh
